version: "3.7"
services:
  flask_app:
    container_name: flask_app
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    volumes:
      - ./flask_app:/flask_app
